seed: 42
dataset:
  kind: synthetic_tabular
  n_samples: 6000
  n_features: 20
  anomaly_fraction: 0.05
  train_frac: 0.7
  val_frac: 0.15
model:
  encoder: mlp
  emb_dim: 64
  hidden_dims: [128, 128]
train:
  batch_size: 256
  epochs: 10
  lr: 1e-3
  temperature: 0.2
detector:
  head: mahalanobis
  knn_k: 10
  ocsvm_nu: 0.05
  score_threshold: auto
