seed: 7
dataset:
  kind: synthetic_timeseries
  n_series: 800
  length: 128
  n_channels: 3
  anomaly_fraction: 0.08
  train_frac: 0.7
  val_frac: 0.15
model:
  encoder: cnn1d
  emb_dim: 64
  cnn_channels: [32, 64]
train:
  batch_size: 64
  epochs: 10
  lr: 1e-3
  temperature: 0.2
detector:
  head: knn
  knn_k: 15
  ocsvm_nu: 0.05
  score_threshold: auto
